kind: Deployment
apiVersion: apps/v1
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: quay.io/ukreddyredhat/test-tekton:goweb
        ports:
        - name: http-server
          containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  ports:
  - port: 8080
    targetPort: http-server
  selector:
    app: guestbook
  type: LoadBalancer
  
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gowebapp
spec:
  rules:
  - host: gowebapp.external.io
    http:
     paths:
     - path: /
       pathType: Prefix
       backend:
        serviceName: guestbook
        servicePort: 8080
