kind: Deployment
apiVersion: apps/v1
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  replicas: 3
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      containers:
      - name: guestbook
        image: quay.io/ukreddyredhat/test-tekton:goweb
        ports:
        - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: guestbook
  labels:
    app: guestbook
spec:
  ports:
  - name: 8080-tcp
    protocol: TCP
    port: 3000
    targetPort: 3000
  selector:
    app: guestbook
    deploymentconfig: guestbook
  type: ClusterIP
  
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gowebapp
spec:
  rules:
  - host: gowebapp.external.io
    http:
     paths:
     - path: /
       backend:
        serviceName: guestbook
        servicePort: 3000
